### ISSUE TITLE
CMake Error "libusb::libusb" not found

### ISSUE THREAD

**Issue by rawnam** [ZhenshengLee/ros2_v4l2_camera#1]
Hi,

I am trying to build v4l2_camera on Ubuntu 22.04 and ROS Humble but getting cmake errors Boost, VTX and libusb. I was able to add Boost and VTK to CMake and it worked but unable to add libusb via Cmake.

CMake Error at CMakeLists.txt:30 (add_library):
  Target "v4l2_camera" links to target "libusb::libusb" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

Please help

**Comment by ZhenshengLee** [comment]
`sudo apt install libusb-dev` and have a try.

**Comment by rawnam** [comment]
That didn't work. Is there a cmake config that can find libusb versions installed in the system? I tried a few hacks from stackoverflow but none of them worked. Also, I couldn't find any usage of this library either. Where is it being used in the project?

**Comment by ZhenshengLee** [comment]
this repo is originally hosted in https://gitlab.com/boldhearts/ros2_v4l2_camera , so for general compiling issue, you could create issues in gitlab, thanks.

**Comment by rawnam** [comment]
the original repo compiles without any issues. Somehow this libusb issue is coming up only on this repository.

**Comment by ZhenshengLee** [comment]
@arukan404  thanks for your report

the outdoor/rolling branch was tested in galactic, and it's confirmed that the code cannot compile correctly in the humble env

I will try to find some time to resolve this issue.

**Comment by rawnam** [comment]
Any thoughts on what we can do to resolve it?

**Comment by rawnam** [comment]
It appears that the linker dependency is due to shm_msgs repository. Any idea how and where is libusb getting linked in shm msgs?

**Comment by rawnam** [comment]
I was able to fix the problem. I added the Findlibusb.cmake from libpcl installation to the CMakeLists and it worked. 
[Findlibusb.txt](https://github.com/ZhenshengLee/ros2_v4l2_camera/files/10169493/Findlibusb.txt)

Facing a new issue though. Linked here #2

**Comment by ZhenshengLee** [comment]
@arukan404  awesome!

> I was able to add Boost and VTK to CMake and it worked but unable to add libusb via Cmake.
> I was able to fix the problem. I added the Findlibusb.cmake from libpcl installation to the CMakeLists and it worked.

Could you please share what you did to solve this issue?
Or you can just create a PR and enjoy open source contributions!

Thanks.

**Comment by rawnam** [comment]
[patch.txt](https://github.com/ZhenshengLee/ros2_v4l2_camera/files/10179338/patch.txt)
I'll create a PR as well
