### ISSUE TITLE
register node

### ISSUE THREAD

**Issue by sgf201** [ZhenshengLee/ros2_v4l2_camera#4]
template<typename Topic>
void V4L2Camera<Topic>::convert_shm(Topic & img) const
{
  auto tracked_object = std::shared_ptr<const void>{};
  auto cvImg = shm_msgs::toCvShare(img, tracked_object);
  auto cvConvertedImg = shm_msgs::cvtColor(cvImg, output_encoding_);
  cvConvertedImg->toImageMsg(img);
}

template<typename Topic>
bool V4L2Camera<Topic>::checkCameraInfo(
  sensor_msgs::msg::Image const & img,
  sensor_msgs::msg::CameraInfo const & ci)
{
  return ci.width == img.width && ci.height == img.height;
}

template<typename Topic>
bool V4L2Camera<Topic>::checkCameraInfo_shm(
  Topic const & img,
  sensor_msgs::msg::CameraInfo const & ci)
{
  return ci.width == img.width && ci.height == img.height;
}

}  // namespace v4l2_camera

// #include "rclcpp_components/register_node_macro.hpp"
// RCLCPP_COMPONENTS_REGISTER_NODE(v4l2_camera::V4L2Camera)
您好，上边这段代码去掉了 COMPONENT_NODE的宏定义，请问这种使用模块的node类是否有啥办法使用这种node注册的宏吗？

**Comment by ZhenshengLee** [comment]
这是一个单纯的cpp编译问题，需要rclcpp支持即可。
It's actually a cpp problem that requires the support from rclcpp.
